version: "3.7"

services:
  
  database:
      image: mysql:8.0
      ports:
          - "3306:3306"
      environment:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: imagems_db

  imagemanager:
    container_name: imagemanager
    build:
      context: .
      dockerfile: Dockerfile
    image: fieldwire/imagemanager:1.0
    ports:
      - "8080:8080"
    depends_on:
      - database  
    restart: on-failure  